# config/_default/menus.en.toml
# see https://github.com/jpanther/congo/blob/dev/config/_default/menus.en.toml

[[main]]
name = "2020"
pageRef = "2020"
weight = 8

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Categories"
pageRef = "categories"
weight = 20

[[main]]
name = "About"
pageRef = "about"
weight = 30

[[main]]
name = "GitHub"
url = "https://github.com/Pen-y-Fan"
weight = 40