# config/_default/menus.en.toml
# see https://github.com/jpanther/congo/blob/dev/config/_default/menus.en.toml

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Tags"
pageRef = "tags"
weight = 20

[[main]]
name = "About"
pageRef = "about"
weight = 30

[[main]]
name = "Portfolio"
pageRef = "portfolio"
weight = 40

[[main]]
name = "GitHub"
url = "https://github.com/Pen-y-Fan"
weight = 50
