# see https://github.com/jpanther/congo/blob/dev/config/_default/params.toml
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

robots = "all"

colorScheme = 'ocean'
autoSwitchAppearance = 'true'
enableCodeCopy = 'true'

mainSections = "posts"

[header]
layout = "basic" # valid options: basic, hamburger, custom
logo = 'img/logo-100x100.jpg'

[footer]
showAppearanceSwitcher = 'true'

[homepage]
layout = "profile"
showRecent = 'true'

[article]
showTableOfContents = 'true'
sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
showSummary = 'true'
showTableOfContents = 'true'